<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10352" started-at="2017-09-25T10:01:32Z" finished-at="2017-09-25T10:01:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10352" started-at="2017-09-25T10:01:32Z" finished-at="2017-09-25T10:01:42Z">
      <class name="executionEngine.CategoryTest">
        <test-method status="PASS" signature="startReport()[pri:0, instance:executionEngine.CategoryTest@42d80b78]" name="startReport" is-config="true" duration-ms="172" started-at="2017-09-25T15:31:32Z" finished-at="2017-09-25T15:31:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="OpenBrowse()[pri:0, instance:executionEngine.CategoryTest@42d80b78]" name="OpenBrowse" is-config="true" duration-ms="6942" started-at="2017-09-25T15:31:32Z" finished-at="2017-09-25T15:31:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowse -->
        <test-method status="FAIL" signature="addcategory()[pri:0, instance:executionEngine.CategoryTest@42d80b78]" name="addcategory" duration-ms="3197" started-at="2017-09-25T15:31:39Z" finished-at="2017-09-25T15:31:42Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utility.RepositoryParser.getLocator(RepositoryParser.java:33)
	at pageObjects.HomePage.Icon_Masters(HomePage.java:43)
	at appModules.HomePageAction.navigate_Category(HomePageAction.java:31)
	at executionEngine.CategoryTest.addcategory(CategoryTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addcategory -->
        <test-method status="FAIL" signature="getResult(org.testng.ITestResult)[pri:0, instance:executionEngine.CategoryTest@42d80b78]" name="getResult" is-config="true" duration-ms="0" started-at="2017-09-25T15:31:42Z" finished-at="2017-09-25T15:31:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addcategory status=FAILURE method=CategoryTest.addcategory()[pri:0, instance:executionEngine.CategoryTest@42d80b78] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at executionEngine.CategoryTest.getResult(CategoryTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:703)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="afterClass()[pri:0, instance:executionEngine.CategoryTest@42d80b78]" name="afterClass" is-config="true" duration-ms="0" started-at="2017-09-25T15:31:42Z" finished-at="2017-09-25T15:31:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="SKIP" signature="teardown()[pri:0, instance:executionEngine.CategoryTest@42d80b78]" name="teardown" is-config="true" duration-ms="0" started-at="2017-09-25T15:31:42Z" finished-at="2017-09-25T15:31:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- executionEngine.CategoryTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
